language: node_js
python: 
  - "3.6"
node_js: stable

notifications:
  email:
    recipients:
      - 875974254@qq.com
      - qinyuanpei@163.com
    on_success: change # default: change
    on_failure: always # default: always

install:
  - npm install
  - sudo apt-get install python3 -y
  - sudo apt-get install python3-pip -y
  - sudo pip3 install -r requirements.txt

script:
  - hexo clean
  - python3 albums.py
  - hexo generate
  - python3 readme.py
  - cp README.md ./public/README.md
  - cp albums.json ./public/albums.json

after_script:
  - git config user.name "qinyuanpei"
  - git config user.email "qinyuanpei@163.com"
  - cd ./public
  - git init
  - git remote add origin master https://github.com/qinyuanpei/qinyuanpe.github.io 
  - git add .
  - git commit -m "Update Blog By TravisCI With Build $TRAVIS_BUILD_NUMBER"
  # Github Pages
  - git push --force --quiet "https://${CI_TOKEN}@${GH_REF}" master:master 
  # Coding Pages
  - git push --force --quiet "https://qinyuanpei:${CO_TOKEN}@${CO_REF}" master:master
  - git tag v0.0.$TRAVIS_BUILD_NUMBER -a -m "Auto Taged By TravisCI With Build $TRAVIS_BUILD_NUMBER"
  # Github Pages
  - git push --quiet "https://${CI_TOKEN}@${GH_REF}" master:master --tags


addons:
  apt:
    update: true

branches:
  only:
    - blog

env:
 global:
   # Github Pages
   - GH_REF: github.com/qinyuanpei/qinyuanpei.github.io
   # Coding Pages
   - CO_REF: git.coding.net/qinyuanpei/qinyuanpei.coding.me.git
