language: node_js
python: stable
node_js: stable

notifications:
  email:
    recipients:
      - 875974254@qq.com
      - qinyuanpei@163.com
    on_success: change # default: change
    on_failure: always # default: always

install:
  - npm install
  - sudo apt-get install python3 -y
  - sudo apt-get install python3-pip -y
  - sudo pip3 install pip -U
  - sudo -H pip config set global.index-url https://mirrors.aliyun.com/pypi/simple/
  - sudo pip install setuptools==33.1.1
  - sudo -H pip3 install -r requirements.txt

script:
  - hexo clean
  - git rev-parse HEAD > VERSION.txt
# - python3 migrate.py 

after_script:
  - echo 'Build Master Repository(Coding Pages)'
  - rm _config.yml
  - mv config-master.yml _config.yml
  - hexo generate
  - python3 readme.py https://blog.yuanpei.me/
  - cp README.md ./public/README.md
  - cp VERSION.txt ./public/VERSION.txt
  #- cp albums.json ./public/albums.json
  - git config user.name "qinyuanpei"
  - git config user.email "qinyuanpei@163.com"
  - cd ./public
  - git init
  - git remote add origin master https://github.com/qinyuanpei/qinyuanpe.github.io 
  - git add .
  - git commit -m "Coding Pages Build (v$TRAVIS_BUILD_NUMBER)"
  - git push --force --quiet "https://${CO_USER}:${CO_TOKEN}@${CO_REF}" master:master
  # Prepare Rebuild
  - cd ..
  - rm -rf ./public
  - hexo clean
  - echo 'Build Salver Repository(Github Pages)'
  - rm _config.yml
  - mv config-salve.yml _config.yml
  - hexo generate
  - python3 readme.py https://qinyuanpei.github.io/
  - cp README.md ./public/README.md
  - cp albums.json ./public/albums.json
  - cp VERSION.txt ./public/VERSION.txt
  - git config user.name "qinyuanpei"
  - git config user.email "qinyuanpei@163.com"
  - cd ./public
  - git init 
  - git remote add origin master https://github.com/qinyuanpei/qinyuanpe.github.io
  - git add .
  - git commit -m "Github Pages Build (v$TRAVIS_BUILD_NUMBER)"
  - git push --force --quiet "https://${CI_TOKEN}@${GH_REF}" master:master
  - git tag v$TRAVIS_BUILD_NUMBER
  - git tag latest
  - git push --quiet "https://${CI_TOKEN}@${GH_REF}" master:master --tags
  # - git fetch origin
  # - git checkout -b blog origin/blog
  # - cd ..
  # - cp README.md ./public/README.md
  # - git add .
  # - git commit -m "Update README.md"
  # - git push "https://${CI_TOKEN}@${GH_REF}" blog:blog

addons:
  apt:
    update: true

branches:
  only:
    - blog

env:
 global:
   # Github Pages
   - GH_REF: github.com/qinyuanpei/qinyuanpei.github.io.git
   # Coding Pages
   - CO_REF: e.coding.net/qinyuanpei/qinyuanpei.coding.me.git
   
   
