
language: node_js
node_js: stable

notifications:
  email:
    recipients:
      - 875974254@qq.com
      - qinyuanpei@163.com
    on_success: change # default: change
    on_failure: always # default: always

# S: Build Lifecycle
install:
  - npm install
  - wget https://www.python.org/ftp/python/3.6.4/Python-3.6.4.tar.xz
  - tar xvf  Python-3.6.4.tar.xz
  - cd ./configure 
  - make && make install
  - pip3 install -r requirements.txt

script:
  - hexo clean
  - hexo generate
  - python3 HexoBlog.py
  - cp README.md ./public/README.md

after_script:
  - cd ./public
  - git init
  - git config user.name "qinyuanpei"
  - git config user.email "qinyuanpei@163.com"
  - git add .
  - git commit -m "Update Blog By TravisCI With Build $TRAVIS_BUILD_NUMBER"
  - git push --force --quiet "https://${CI_TOKEN}@${GH_REF}" master:master
  - git tag v0.0.$TRAVIS_BUILD_NUMBER -a -m "Auto Taged By TravisCI With Build $TRAVIS_BUILD_NUMBER"
  - git push --quiet "https://${CI_TOKEN}@${GH_REF}" master:master --tags
# E: Build LifeCycle

branches:
  only:
    - blog

env:
 global:
   - GH_REF: github.com/qinyuanpei/qinyuanpei.github.io
