name: Hexo CI

on:
  push:
    branches:    
      - blog

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: 8.x
    - name: Install Packages
      run: npm install 
    - name: Clean & Generate
      run: hexo clean & hexo generate
      env:
        CI: true
