name: Hexo CI

on:
  push:
    branches:    
      - blog

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: 8.x
    - name: Setup Python
      run: |
        - sudo apt-get install python3 -y
        - sudo apt-get install python3-pip -y
        - sudo pip3 install pip -U
        - sudo -H pip config set global.index-url https://pypi.tuna.tsinghua.edu.cn/simple
        - sudo -H pip3 install -r requirements.txt
    - name: Setup Hexo
      run: npm install hexo-cli -g
    - name: Install Packages
      run: npm install
    - name: Clean & Generate
      run: | 
       - hexo clean
       - git rev-parse HEAD > VERSION.txt
    - name: Deploy Github Pages
      run: |
       - rm _config.yml
       - mv config-salve.yml _config.yml
       - hexo recommend
       - hexo douban
       - hexo generate
       - python3 readme.py https://qinyuanpei.github.io/
       - cp README.md ./public/README.md
       - cp VERSION.txt ./public/VERSION.txt
       - git config user.name "qinyuanpei"
       - git config user.email "qinyuanpei@163.com"
       - cd ./public
       - git init 
       - git remote add origin master https://github.com/qinyuanpei/qinyuanpe.github.io
       - git add .
       - git commit -m "Update Blog By Github Actions"
       - git push --force --quiet "https://${CI_TOKEN}@${GH_REF}" master:master
      
      env:
        CI: true
        GH_REF: github.com/qinyuanpei/qinyuanpei.github.io
        CI_TOKEN: ${{ secrets.CI_TOKEN }}
